import { launch, BASE } from './e2e-lib.mjs';
const S = '/sessions/youthful-laughing-lovelace/mnt/outputs/shots';
const { browser, page } = await launch();
await page.goto(`${BASE}/community`, { waitUntil: 'domcontentloaded', timeout: 25000 }).catch(()=>{});
await page.waitForTimeout(3000);
console.log('mentor names on page:', await page.locator('text=Priya Sharma').count() + (await page.locator('text=Sneha Iyer').count()));
await page.locator('button:has-text("Events")').click();
await page.waitForTimeout(2000);
const signup = page.locator('button:has-text("Sign Up")').first();
await signup.click();
await page.waitForTimeout(2500);
const cancel = await page.locator('button:has-text("Cancel Registration")').count();
console.log('event registered (cancel visible):', cancel > 0);
await page.locator('button:has-text("Group Discussion")').click();
await page.waitForTimeout(2500);
await page.screenshot({ path: `${S}/community-groups.png`, fullPage: true });
const joins = await page.locator('button:has-text("Join")').count();
console.log('group join buttons:', joins);
await browser.close();
